export const systemOrder = [
    'NES',
    'Super Nintendo',
    'Nintendo 64',
    'GameCube',
    'Wii',
    'Wii U',
    'Switch',
    'Game Boy',
    'Game Boy Color',
    'Game Boy Advance',
    'DS',
    '3DS',
    'PlayStation',
    'PlayStation 2',
    'PlayStation 3',
    'PlayStation 4',
    'PlayStation Portable',
    'Xbox',
    'Xbox 360',
    'Xbox One',
    'Master System',
    'Genesis',
    'PC',
    'Oculus Rift',
    'Oculus Quest',
    'Android',
    'Arcade',
];
