type Query {
    compilations: [Compilation!]!
}

type Mutation {
    createCompilation(input: CreateCompilationInput!): Compilation!
    updateCompilation(input: UpdateCompilationInput!): Compilation!
    deleteCompilation(id: ID!): Compilation!
}

type Compilation {
    id: ID!
    title: String!
    games: [Game!]!
}

input RelateCompilationInput {
    id: ID
    title: String
}

input CreateCompilationInput {
    title: String!
}

input UpdateCompilationInput {
    id: ID!
    title: String
}

