type Query {
    games: [Game!]!
}

type Mutation {
    createGame(input: CreateGameInput!): Game!
    updateGame(input: UpdateGameInput!): Game!
    fetchGameData(input: FetchGameDataInput!): FetchGameDataResult!
    skipGame(id: ID!): Game!
    deleteGame(id: ID!): Game!
}

type Game {
    id: ID!
    system: System!
    compilation: Compilation
    developer: Developer!
    genres: [Genre!]!
    dlcs: [Dlc!]!
    title: String!
    rating: Int!
    release: Int!
    description: String!
    youTubeId: String!
    status: GameStatus!
    skipCount: Int!
    updatedAt: DateTime!
    franchises: [Franchise!]!
    timeToBeat: Float
    criticRating: Int
    country: String
}

enum GameStatus {
    active
    planned
    completed
    dropped
}

input CreateGameInput {
    title: String!
    rating: Int!
    release: Int!
    description: String!
    youTubeId: String!
    system: RelateSystemInput!
    developer: RelateDeveloperInput!
    genres: [RelateGenreInput!]!
    compilation: RelateCompilationInput
    status: GameStatus!
    franchises: [RelateFranchiseInput!]
    timeToBeat: Float
    criticRating: Int
    country: String
}

input UpdateGameInput {
    id: ID!
    title: String
    rating: Int
    release: Int
    description: String
    youTubeId: String
    system: RelateSystemInput
    developer: RelateDeveloperInput
    genres: [RelateGenreInput!]
    compilation: RelateCompilationInput
    status: GameStatus
    franchises: [RelateFranchiseInput!]
    timeToBeat: Float
    criticRating: Int
    country: String
}

input FetchGameDataInput {
    title: String!
    system: String!
    compilation: String
    aiInstructions: String
    types: [String!]
}

type FetchGameDataResult {
    developer: String
    country: String
    genres: [String!]
    release: Int
    description: String
    youTubeId: String
    franchise: String
    timeToBeat: Float
    criticRating: Int
}
